### ISSUE TITLE
Add tag and releases according to npm releases

### ISSUE THREAD

**Issue by alagane** [maxime1992/ngx-hover-opacity#10]
Hi,

On NPM module page, there is more versions than those tagged and released on GitHub (https://www.npmjs.com/package/ngx-hover-opacity). It would be great that versions on GitHub match versions on NPM.

Missing versions on GitHub are:
 * 0.3.1
 * 0.3.0
 * 0.2.1
 * 0.1.0

Thank you for you work!

**Comment by maxime1992** [comment]
Hi @alagane 

> Thank you for you work!

Thanks :smile_cat: 

It appears that the latest version is correctly published on github too. I'm going to assume this has been fixed as I think the github token was invalidated for a while and I did restore it (after a few releases).

As the latest is in the published versions on Github I'm gonna close this for now but if you notice that again with a release > 1.0.0 please reopen :)
